import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import CssBaseline from '@mui/material/CssBaseline'
import { Inter } from 'next/font/google'
import './globals.css'

import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body className={inter.className + ' h-screen overflow-hidden'}>
        <CssBaseline />
        {children}
      </body>
    </html>
  )
}
